[package]
name = "bevy_gps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy="0.13"
bevy_wasm_window_resize = "0.3.0"
